[package]
name = "tapi-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
tokio = {version = "1", features = ["full"]}
reqwest = "0.11.18"
futures = "0.3.28"
pin-project-lite = "0.2.9"